// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQOzGiDgOFdrVT-8p-h4IjrodVj4Pn_s',
    appId: '1:753065970058:web:e82ff03c74ff3833e7a073',
    messagingSenderId: '753065970058',
    projectId: 'quiz-game-e082c',
    authDomain: 'quiz-game-e082c.firebaseapp.com',
    databaseURL: 'https://quiz-game-e082c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-game-e082c.firebasestorage.app',
    measurementId: 'G-KQE86J3RKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApICCrB6JQk4q2JyEmXig-_rvtn0xNwk',
    appId: '1:753065970058:android:e7d10c4d4a16a8fce7a073',
    messagingSenderId: '753065970058',
    projectId: 'quiz-game-e082c',
    databaseURL: 'https://quiz-game-e082c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-game-e082c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqXAnTYzQB5WazNSjkErCgJ3tlW_EF9fM',
    appId: '1:753065970058:ios:b6b097f2a4f3c184e7a073',
    messagingSenderId: '753065970058',
    projectId: 'quiz-game-e082c',
    databaseURL: 'https://quiz-game-e082c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-game-e082c.firebasestorage.app',
    iosBundleId: 'com.example.quizGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqXAnTYzQB5WazNSjkErCgJ3tlW_EF9fM',
    appId: '1:753065970058:ios:b6b097f2a4f3c184e7a073',
    messagingSenderId: '753065970058',
    projectId: 'quiz-game-e082c',
    databaseURL: 'https://quiz-game-e082c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-game-e082c.firebasestorage.app',
    iosBundleId: 'com.example.quizGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQQOzGiDgOFdrVT-8p-h4IjrodVj4Pn_s',
    appId: '1:753065970058:web:89abfdcb64115249e7a073',
    messagingSenderId: '753065970058',
    projectId: 'quiz-game-e082c',
    authDomain: 'quiz-game-e082c.firebaseapp.com',
    databaseURL: 'https://quiz-game-e082c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quiz-game-e082c.firebasestorage.app',
    measurementId: 'G-9H01P23XNW',
  );
}
